**numpy stands for Numerical Python**

1. Create and manipulate large arrays

In [2]:
import numpy as np

**1.Why Use Numphy**

In [ ]:
np_arr = np.array([1,2,3,4,5])

np_arr
np_arr+10       #array([11, 12, 13, 14, 15])
np_arr          #array([1, 2, 3, 4, 5])
type(np_arr)    #np_arr = np.array([1,2,3,4,5])

numpy.ndarray

In [8]:
import time
size = 100000

start = time.time()
basic_list = list(range(size))
res = [x+1 for x in basic_list]
time_python = time.time() - start
print(f"Basic List time is {time_python:.6f}")


start = time.time()
numpy_list = np.arange(size)
res = numpy_list + 1
time_python = time.time() - start
print(f"Numpy List time is {time_python:.6f}")

Basic List time is 0.003255
Numpy List time is 0.002019


**2.Creating numphy Array**


In [9]:
# List method
np_arr1 = np.array([1,2,3,4,5])

# Arange        start,stop,steps
np_arr2 = np.arange(0,10,2)

#linspace       start, stop, parts
np_arr3 = np.linspace(0,1,10)

# Aray of Zero
np_arr4 = np.zeros(5)

#Array of ones
np_arr5 = np.ones(5)

# Full array   size, fill num
np_arr6 = np.full(5,10)

# Identity matrix
np_arr7 = np.eye(3)

# Randon
np_arr8 = np.random.rand(10)

# Random integer        start, stop, size
np_arr9 = np.random.randint(0,10,size=5)



print(np_arr1)
print(np_arr2)
print(np_arr3)
print(np_arr4)
print(np_arr5)
print(np_arr6)
print(np_arr7)
print(np_arr8)
print(np_arr9)

[1 2 3 4 5]
[0 2 4 6 8]
[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]
[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]
[10 10 10 10 10]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[0.27174801 0.68422419 0.17319408 0.12821922 0.32727257 0.80656104
 0.98674383 0.69860654 0.50088811 0.33493117]
[5 9 2 2 7]


**3.Datatypes or dtypes**

In [10]:
arr_int = np.array([1,2,3])
arr_flo = np.array([1.,2.,3.])
arr_mix = np.array([1.0,2,3])

print(arr_int.dtype)
print(arr_flo.dtype)
print(arr_mix.dtype)

arr_defined = np.array([1,2,3], dtype='float32')
print(arr_defined.dtype)

arr_new = arr_int.astype('float32')
print(arr_new.dtype)


int64
float64
float64
float32
float32



**4. Multi-Dimensional Array**

In [14]:
matrix_1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matrix_1)
print(matrix_1.dtype)
print(f'Shape {matrix_1.shape}')
print(f'Dimension {matrix_1.ndim}')

[[1 2 3]
 [4 5 6]
 [7 8 9]]
int64
Shape (3, 3)
Dimension 2


In [19]:
matrix_2 = np.random.rand(3,3)
print(matrix_2)

zero_matrix = np.zeros((3,3))
one_matrix = np.ones((3,3))

print(zero_matrix)
print(one_matrix)

[[0.9260819  0.13636218 0.70996156]
 [0.97528849 0.21988899 0.94176473]
 [0.48236942 0.81530247 0.56003502]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
matrix_3d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
(2, 2, 3)


In [25]:
print(matrix_3d)
print(f'Total number of elements : {matrix_3d.size}')
print(f'Total No of bytes used by each : {matrix_3d.nbytes}')
print(f'No bytes used by one element : {matrix_3d.itemsize}')
print(f'Dimension : {matrix_3d.ndim}')
print(f'Dtype : {matrix_3d.dtype}')
print(f'Shape : {matrix_3d.shape}')
print(f'Transpose : {matrix_3d.T}')

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
Total number of elements : 12
Total No of bytes used by each : 96
No bytes used by one element : 8
Dimension : 3
Dtype : int64
Shape : (2, 2, 3)
Transpose : [[[ 1  7]
  [ 4 10]]

 [[ 2  8]
  [ 5 11]]

 [[ 3  9]
  [ 6 12]]]


**5. Indexing & Slicing**

In [ ]:
np_arr = np.random.randint(0,100, size= 10)


[71 81 60 40 51 42 72 63 42 48]
71
48
[48 42 63 72 42 51 40 60 81 71]


In [ ]:
print(np_arr)
print(np_arr[0])
print(np_arr[-1])
print(np_arr[::-1])

In [17]:
arr = np.random.randint(0,100, size= (4,4))

arr

array([[ 8, 90, 63, 34],
       [46, 62, 86, 10],
       [17, 14, 94, 10],
       [42, 78, 15, 37]])

In [24]:
print(arr[0,0])             #Prints a specific element
print(arr[0, 0:])           #Prints only column
print(arr[0: , 0])          #Prints only row
print(arr[0: , 0:])         #Prints all elements
print(arr[1:3, 1:3])       #Prints a specific part of the array

8
[ 8 90 63 34]
[ 8 46 17 42]
[[ 8 90 63 34]
 [46 62 86 10]
 [17 14 94 10]
 [42 78 15 37]]
[[62 86]
 [14 94]]


In [27]:
print(np_arr[np_arr > 50])   #Prints all elements greater than 50
print(np_arr[np_arr % 2 == 0])   #Prints all elements divisble by 2
print(arr[0: , 0:][arr[0: , 0:] > 50])   #Prints all elements greater than 50

[71 81 60 51 72 63]
[60 40 42 72 42 48]
[90 63 62 86 94 78]


**6. Array Operations**

In [44]:
a = np.random.randint(1,100, size= 6)
b = np.random.randint(1,100, size= 6)

print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a**2)
print(np.sqrt(b))


[149 111  42 100  38 143]
[ 37 -75  38 -56 -16 -29]
[5208 1674   80 1716  297 4902]
[ 1.66071429  0.19354839 20.          0.28205128  0.40740741  0.6627907 ]
[8649  324 1600  484  121 3249]
[7.48331477 9.64365076 1.41421356 8.83176087 5.19615242 9.2736185 ]


In [35]:
print(a > b)
print(a[a>b])

[False False  True  True  True]
[68 28 89]


**7. Array Manipulation**

In [53]:
print(np_arr)

#Doesn't store the changed value
reshape_arr = np.reshape(np_arr, (2,5))
print(reshape_arr)

print(np_arr.reshape(2,5))
print(np_arr)
print(reshape_arr)
print()

flatten_arr = reshape_arr.flatten()
print(flatten_arr)
print()

new_arr = np.reshape(np_arr,(5,-1))     # -1 makes the seceond value automatic
print(new_arr)
print(new_arr.T)                        # Transpose of new_arr



[71 81 60 40 51 42 72 63 42 48]
[[71 81 60 40 51]
 [42 72 63 42 48]]
[[71 81 60 40 51]
 [42 72 63 42 48]]
[71 81 60 40 51 42 72 63 42 48]
[[71 81 60 40 51]
 [42 72 63 42 48]]

[71 81 60 40 51 42 72 63 42 48]

[[71 81]
 [60 40]
 [51 42]
 [72 63]
 [42 48]]
[[71 60 51 72 42]
 [81 40 42 63 48]]


In [52]:

a1 = np.reshape(a, (2,-1))
b1 = np.reshape(b, (2,-1))

print()
print(a1)
print(b1)
print()
print(np.vstack((a1,b1)))
print(np.hstack((a1,b1)))
print(np.concatenate((a1,b1), axis=0))
print(np.concatenate((a1,b1), axis=1))


[[93 18 40]
 [22 11 57]]
[[56 93  2]
 [78 27 86]]

[[93 18 40]
 [22 11 57]
 [56 93  2]
 [78 27 86]]
[[93 18 40 56 93  2]
 [22 11 57 78 27 86]]
[[93 18 40]
 [22 11 57]
 [56 93  2]
 [78 27 86]]
[[93 18 40 56 93  2]
 [22 11 57 78 27 86]]


In [55]:
print(np.sum(a1, axis=0))
print(np.sum(a1, axis=1))
print(np.sum(a1))

[115  29  97]
[151  90]
241


**8.Statistics**

    Any matrix can be done with this kind of methods, with help of axis=

In [60]:
print(f'Sum is : {np.sum(a)}')
print(f'Mean is : {np.mean(a)}')
print(f'Median is : {np.median(a)}')
print(f'Standard Deviance is : {np.std(a)}')
print(f'Variance is : {np.var(a)}')
print(f'Minimum is : {np.min(a)}')
print(f'Index of Minimum is : {np.argmin(a)}')
print(f'Maximum is : {np.max(a)}')
print(f'Index of Maximum is : {np.argmax(a)}')

Sum is : 241
Mean is : 40.166666666666664
Median is : 31.0
Standard Deviance is : 28.127191272661566
Variance is : 791.138888888889
Minimum is : 11
Index of Minimum is : 4
Maximum is : 93
Index of Maximum is : 0


**9. Linear Algebra**

In [69]:
a = np.random.randint(0,10,size=(2,2))
b = np.random.randint(0,10,size=(2,2))

print(a)
print(b)
print(f'Linear Algebra {a*b}')
print(f'Dot multiplication {np.dot(a,b)}')      #Matrix multiplication

print(f'Determinant : {np.linalg.det(a)}')
print(f'Inverse: {np.linalg.inv(a)}')
print(f'Transpose: {a.T}')

eigenvals, eigenvec = np.linalg.eigh(a)
print(f'Eigen Values : {eigenvals}')
print(f'Eigen Vectors : {eigenvec}')


[[9 6]
 [1 6]]
[[1 6]
 [4 3]]
Linear Algebra [[ 9 36]
 [ 4 18]]
Dot multiplication [[33 72]
 [25 24]]
Determinant : 48.00000000000001
Inverse: [[ 0.125      -0.125     ]
 [-0.02083333  0.1875    ]]
Transpose: [[9 1]
 [6 6]]
Eigen Values : [5.69722436 9.30277564]
Eigen Vectors : [[ 0.28978415 -0.95709203]
 [-0.95709203 -0.28978415]]


**10.Useful Array Methods**

In [82]:
a = np.random.randint(0,10,size=15)
b = np.random.randint(0,10,size=15)

#Sorting

print(f'Original Value : {a}')
print(f'Sorts and produces a copy : {np.sort(a)}')
print(f'Does not change the original array : {a}')

a.sort()
print(f'Sorts the original array : {a}')

#Unique

print(f'Unique values : {np.unique(a)}')


a = np.random.randint(0,10,size=15)

Original Value : [3 8 5 9 9 7 7 7 0 5 4 5 5 4 2]
Sorts and produces a copy : [0 2 3 4 4 5 5 5 5 7 7 7 8 9 9]
Does not change the original array : [3 8 5 9 9 7 7 7 0 5 4 5 5 4 2]
Sorts the original array : [0 2 3 4 4 5 5 5 5 7 7 7 8 9 9]
Unique values : [0 2 3 4 5 7 8 9]


In [84]:
print(a)
print(b)
print()
#Search
print(f'Search value 5 : {np.where(a==5)}')
print(f'Search value > 5 : {np.where(a>5)}')
print(f'Search value > 5 : {a[np.where(a>5)]}')


#Stacking
print(f'Vertical stack : {np.vstack((a,b))}')
print(f'Horizontal stack : {np.hstack((a,b))}')
print(f'Column stack : {np.column_stack((a,b))}')

[1 4 9 0 6 2 4 5 5 0 3 2 9 2 3]
[6 3 2 9 8 6 6 5 3 4 3 8 9 5 4]

Search value 5 : (array([7, 8]),)
Search value > 5 : (array([ 2,  4, 12]),)
Search value > 5 : [9 6 9]
Vertical stack : [[1 4 9 0 6 2 4 5 5 0 3 2 9 2 3]
 [6 3 2 9 8 6 6 5 3 4 3 8 9 5 4]]
Horizontal stack : [1 4 9 0 6 2 4 5 5 0 3 2 9 2 3 6 3 2 9 8 6 6 5 3 4 3 8 9 5 4]
Column stack : [[1 6]
 [4 3]
 [9 2]
 [0 9]
 [6 8]
 [2 6]
 [4 6]
 [5 5]
 [5 3]
 [0 4]
 [3 3]
 [2 8]
 [9 9]
 [2 5]
 [3 4]]


**11. How can numphy be used for image**

In [87]:
img = np.random.randint(0,256,size=(10,10))
print(img)

[[ 63 241  12 201  22  23 119  58  25 115]
 [228 252 113 195 104  88  68  33  89 242]
 [ 40  62 228 132 168 249  18 167 128 255]
 [ 86 111 226 205  64 211  33 172 170 167]
 [206 236  20  56  21 155 235 224  60  94]
 [135 200 179  88  90 132 165 158 165 112]
 [ 19  57 182  44 101  53 204  81 176  99]
 [ 29  89  38 185 210 109  92 215  15 206]
 [ 75 214 177  90 239  11 202 232 208 216]
 [130  65 204 200 182  99 104  99  56  99]]


In [ ]:
print('Image statsics')
print(f'Brightness: {np.mean(img)}')
print(f'Contrast: {np.std(img)}')
print(f'Min pixel: {np.min(img)}')
print(f'Max pixel: {np.max(img)}')



Image statsics
Brightness: 130.2
Contrast: 72.81030146895424
Min pixel: 11
Max pixel: 255


In [ ]:
brighter = np.clip(img + 50,0,255)
print(f'Old Brightness : {np.mean(img)}')
print(f'New Brightness : {np.mean(brighter)}')

Old Brightness : 130.2
New Brightness : 175.52


In [91]:
contrast = np.clip(img*1.5, 0,255)
print(f'Old Contrast : {np.std(img)}')
print(f'New Contrast : {np.std(brighter)}')

Old Contrast : 72.81030146895424
New Contrast : 66.53126783701029
