**numpy stands for Numerical Python**

1. Create and manipulate large arrays

In [1]:
import numpy as np

**1.Why Use Numphy**

In [8]:
np_arr = np.array([1,2,3,4,5])

np_arr
np_arr+10       #array([11, 12, 13, 14, 15])
np_arr          #array([1, 2, 3, 4, 5])
type(np_arr)    #np_arr = np.array([1,2,3,4,5])

numpy.ndarray

In [10]:
import time
size = 100000

start = time.time()
basic_list = list(range(size))
res = [x+1 for x in basic_list]
time_python = time.time() - start
print(f"Basic List time is {time_python:.6f}")


start = time.time()
numpy_list = np.arange(size)
res = numpy_list + 1
time_python = time.time() - start
print(f"Numpy List time is {time_python:.6f}")

Basic List time is 0.004856
Numpy List time is 0.001104


**2.Creating numphy Array**


In [ ]:
# List method
np_arr1 = np.array([1,2,3,4,5])

# Arange        start,stop,steps
np_arr2 = np.arange(0,10,2)

#linspace       start, stop, parts
np_arr3 = np.linspace(0,1,10)

# Aray of Zero
np_arr4 = np.zeros(5)

#Array of ones
np_arr5 = np.ones(5)

# Full array   size, fill num
np_arr6 = np.full(5,10)

# Identity matrix
np_arr7 = np.eye(3)

# Randon
np_arr8 = np.random.rand(10)

# Random integer        start, stop, size
np_arr9 = np.random.randint(0,10,size=5)



print(np_arr1)
print(np_arr2)
print(np_arr3)
print(np_arr4)
print(np_arr5)
print(np_arr6)
print(np_arr7)
print(np_arr8)
print(np_arr9)

[1 2 3 4 5]
[0 2 4 6 8]
[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]
[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]
[10 10 10 10 10]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[0.50079106 0.81446076 0.33209586 0.13296167 0.84040627 0.55138142
 0.90168923 0.34030057 0.64648504 0.3684012 ]
[5 9 3 0 9]


**3.Datatypes or dtypes**